"""Task 1: deterministic Python source discovery for a cloned repository.

The parser consumes one file at a time, so discovery returns only
metadata.  It does not read all source files into memory.  Test/setup/generated
sources are excluded using explicit, documented rules and the result is sorted
by POSIX relative path so two runs over the same checkout produce the same
manifest.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import sys
from typing import Sequence


# Directory names are matched case-insensitively.  Pattern-based test directory
# matching is handled separately in ``_is_excluded_dir``.
EXCLUDE_DIRS = {
    ".eggs",
    ".git",
    ".github",
    ".mypy_cache",
    ".nox",
    ".pytest_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "_generated",
    "auto_generated",
    "autogenerated",
    "build",
    "dist",
    "env",
    "examples",
    "generated",
    "htmlcov",
    "node_modules",
    "test",
    "testing",
    "tests",
    "venv",
}

# Exact Python filenames excluded from the parser input.  ``setup.cfg`` is not
# listed because discovery already ignores every non-.py file.
EXCLUDE_FILES = {
    "conftest.py",
    "setup.py",
}

EXCLUDE_SUFFIXES = (
    "_generated.py",
    "_gen.py",
    "_pb2.py",
    "_pb2_grpc.py",
)

# Generated-code tools normally place one of these declarations near the top.
# Looking only at the header avoids rejecting ordinary modules that merely talk
# about generated code later in a docstring or comment.
GENERATED_HEADER_MARKERS = (
    "@generated",
    "auto-generated file",
    "autogenerated file",
    "automatically generated",
    "code generated by",
    "generated by the protocol buffer compiler",
    "this file was generated by",
)
GENERATED_HEADER_BYTES = 4096


def _sort_key(value: str) -> tuple[str, str]:
    """Return a deterministic, case-insensitive ordering with a tie-breaker."""
    return value.casefold(), value


def _is_excluded_dir(dirname: str) -> bool:
    """Return whether a directory is infrastructure, generated, or test-only."""
    name = dirname.casefold()
    return (
        name in EXCLUDE_DIRS
        or name.startswith("test_")
        or name.endswith("_test")
        or name.endswith("_tests")
    )


def _is_excluded_file(filename: str) -> bool:
    """Return whether a Python filename is setup, generated, or test-only."""
    name = filename.casefold()
    stem, suffix = os.path.splitext(name)
    if suffix != ".py":
        return True
    if name in EXCLUDE_FILES or name.endswith(EXCLUDE_SUFFIXES):
        return True
    return (
        stem in {"test", "tests"}
        or stem.startswith("test_")
        or stem.endswith("_test")
        or stem.endswith("_tests")
    )


def _has_generated_header(file_path: Path) -> bool:
    """Detect a conventional generated-code declaration in a source header."""
    with file_path.open("rb") as source:
        header = source.read(GENERATED_HEADER_BYTES).decode("utf-8", errors="ignore")
    normalized_header = header.casefold()
    return any(marker in normalized_header for marker in GENERATED_HEADER_MARKERS)


def compute_file_hash(file_path: str | os.PathLike[str]) -> str:
    """Compute a streaming SHA-256 content hash without loading the file at once."""
    hasher = hashlib.sha256()
    with open(file_path, "rb") as source:
        for chunk in iter(lambda: source.read(65536), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def _validated_repo_root(repo_path: str | os.PathLike[str]) -> Path:
    """Resolve a repository path and fail clearly for invalid input."""
    root = Path(repo_path).expanduser().resolve()
    if not root.exists():
        raise FileNotFoundError(f"Repository path does not exist: {root}")
    if not root.is_dir():
        raise NotADirectoryError(f"Repository path is not a directory: {root}")
    return root


def discover_python_files(repo_path: str | os.PathLike[str]) -> list[dict]:
    """Discover parseable Python sources under ``repo_path``.

    The returned manifest is globally sorted by ``relative_path`` and each path
    uses ``/`` regardless of the host operating system.  Invalid input raises a
    descriptive exception instead of silently returning an empty manifest.
    Files that disappear or become unreadable during the scan are skipped so a
    concurrent checkout update cannot abort the complete discovery run.
    """
    repo_root = _validated_repo_root(repo_path)
    discovered: list[dict] = []

    for root, dirs, files in os.walk(repo_root, followlinks=False):
        dirs[:] = sorted(
            (dirname for dirname in dirs if not _is_excluded_dir(dirname)),
            key=_sort_key,
        )

        for filename in sorted(files, key=_sort_key):
            if _is_excluded_file(filename):
                continue

            absolute_path = Path(root, filename)
            try:
                if not absolute_path.is_file() or _has_generated_header(absolute_path):
                    continue
                size = absolute_path.stat().st_size
                file_hash = compute_file_hash(absolute_path)
            except OSError:
                continue

            discovered.append(
                {
                    "relative_path": absolute_path.relative_to(repo_root).as_posix(),
                    "absolute_path": str(absolute_path.resolve()),
                    "file_size_bytes": size,
                    "file_hash": file_hash,
                }
            )

    discovered.sort(key=lambda item: _sort_key(item["relative_path"]))
    return discovered


def _build_argument_parser() -> argparse.ArgumentParser:
    project_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Discover non-test Python sources in a cloned repository."
    )
    parser.add_argument(
        "repo_path",
        nargs="?",
        default=str(project_root / "lerobot"),
        help="cloned repository root (default: <project>/lerobot)",
    )
    parser.add_argument(
        "--output",
        default=str(project_root / "discovered_files.json"),
        help="manifest JSON path (default: <project>/discovered_files.json)",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Run discovery from the command line and write its JSON manifest."""
    args = _build_argument_parser().parse_args(argv)
    try:
        repo_root = _validated_repo_root(args.repo_path)
        python_files = discover_python_files(repo_root)
    except (FileNotFoundError, NotADirectoryError, PermissionError) as error:
        print(f"[Discovery] ERROR: {error}", file=sys.stderr)
        return 2

    output_path = Path(args.output).expanduser().resolve()
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8", newline="\n") as output:
            json.dump(python_files, output, indent=2, ensure_ascii=False)
            output.write("\n")
    except OSError as error:
        print(f"[Discovery] ERROR: cannot write {output_path}: {error}", file=sys.stderr)
        return 2

    print(f"[Discovery] Repository: {repo_root}")
    print(f"[Discovery] Python source files: {len(python_files)}")
    for item in python_files[:10]:
        print(f"  - {item['relative_path']} ({item['file_size_bytes']} bytes)")
    print(f"[Discovery] Manifest: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
